version: "3.8"

services:
  database:
    image: percona
    container_name: percona
    ports:
        - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: percona

  phpmyadmin:
    image: phpmyadmin
    container_name: php
    ports:
      - 8080:80
    links:
      - database:db

  wordpress:
    image: wordpress
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: percona
      
    ports:
      - 20080:80
    links:
      - database:db
